plugins {
    id 'java'
}

group = 'me.coopersully.halara'
version = '1.7'

repositories {
    mavenCentral()
    maven {
        name = 'purpur'
        url = uri('https://repo.purpurmc.org/snapshots')
    }
}

dependencies {
    compileOnly 'org.purpurmc.purpur:purpur-api:26.2.build.2608-stable'

    testImplementation platform('org.junit:junit-bom:6.1.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

tasks.named('processResources') {
    def props = [version: project.version]
    inputs.properties(props)
    filteringCharset = 'UTF-8'
    filesMatching('plugin.yml') {
        expand(props)
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
